version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: task_manager_db
    environment:
      MYSQL_ROOT_PASSWORD: 2d8ccb9f3d83be83c0db0ff2c3ee24b7
      MYSQL_DATABASE: todo_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 2ecb1536b904e1e7213bdf65b5344e12dca84e76
    ports:
      - '4306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - task_manager_network

volumes:
  mysql_data:

networks:
  task_manager_network: